name: Validate with hassfest

permissions:
  contents: read

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    steps:
      - uses: "actions/checkout@v6"
        with:
          persist-credentials: false
      - uses: home-assistant/actions/hassfest@master
